// String Reference
let alphabet = 'ABCDEFGHIJKLMNOPQRSTUVWXYZ';
console.log(alphabet.length);
console.log(alphabet[0]);
console.log(alphabet.at(0));
console.log(alphabet.charAt(0));
console.log(alphabet.charCodeAt(0));
console.log(String.fromCharCode(65));
console.log(alphabet.codePointAt(0));
console.log(String.fromCodePoint(65));
console.log(alphabet.concat(' ', alphabet));
console.log(alphabet.slice(0, 10));
console.log(alphabet.substring(0, 10));
console.log(alphabet.toLowerCase());
console.log(alphabet.toUpperCase());
console.log(alphabet.toLocaleLowerCase());
console.log(alphabet.toLocaleUpperCase());
console.log(alphabet.isWellFormed());
console.log(alphabet.toWellFormed());
console.log(alphabet.trim());
console.log(alphabet.trimStart());
console.log(alphabet.trimEnd());
console.log(alphabet.padStart(30, '-'));
console.log(alphabet.padEnd(30, '-'));
console.log(alphabet.repeat(2));
console.log(alphabet.replace('ABC', 'abc'));
console.log(alphabet.replace(/ABC/i, 'abc'));
console.log(alphabet.replace(/ABC/g, 'abc'));
console.log(alphabet.replace(/ABC/gi, 'abc'));
console.log(alphabet.replaceAll(/ABC/g, 'abc'));
console.log(alphabet.replaceAll(/ABC/gi, 'abc'));
console.log(alphabet.split(''));
let txt = "Please locate where 'locate' occurs!";
console.log(txt.indexOf('locate'));
console.log(txt.lastIndexOf('locate'));
console.log(txt.search('where'));
console.log(txt.search(/occurs/));
let txt1 = 'The rain in SPAIN stays mainly in the plain';
console.log(txt1.match('ain'));
console.log(txt1.match(/ain/));
console.log(txt1.match(/ain/g));
console.log(txt1.match(/ain/gi));
console.log(txt1.matchAll('ain'));
console.log(txt1.matchAll(/ain/g));
console.log(txt1.matchAll(/ain/gi));
console.log(txt1.includes('ain'));
console.log(txt1.startsWith('The'));
console.log(txt1.endsWith('plain'));

// Number Reference
